replicaCount: 1
fullnameOverride: "app2"
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ""
      paths:
        - path: /app2
          pathType: Prefix
extraConfigMap:
  enabled: true
  content: "<h1>Hello from App2 </h1>"
